#!/bin/bash
# File is not using .sh extension to avoid changing its own contents during
# sed lines.

## =================================================================================##
##                                                                                  ||
##                                     PREAMBLE                                     ||
##                                                                                  ||
## =================================================================================##
## PURPOSE:                                                                         ||
## Creates directory structure given in the FilePaths.txt and allows the user to    ||
## remove any mention of 'module load' or 'module purge'.                           ||
## =================================================================================##
## AUTHOR: Sam Fletcher                                                             ||
## CONTACT: s.o.fletcher@exeter.ac.uk                                               ||
## CREATED: January 2024                                                            ||
## =================================================================================##
## DEPENDENCIES: sed                                                                ||
## =================================================================================##
## INPUTS:                                                                          ||
## $1 -> Full (or relative) file path for configuation file directory               ||
## =================================================================================##

# Configuration file is required for file paths

configuration_directory=$1

source "${configuration_directory}/FilePaths.txt" || \
{ echo "The configuration file does not exist in the specified location: \
${configuration_directory}"; exit 1; }

## ============================== ##
##   CREATION OF FILE STRUCTURE   ##
## ============================== ##

mkdir -p "${SUBSAMPLED_DIR}" "${BINARY_DIR}" "${MODEL_DIR}" \
"${OPTIMUM_STATES_DIR}" "${LD_ASSESSMENT_DIR}" "${BIG_MODELS_DIR}"

## ============================= ##
##   DELETE UOE SPECIFIC LINES   ##
## ============================= ##

cd "${SCRIPT_DIR}" || \
{ echo "The configuration file does not point to the correct script directory: \
${SCRIPT_DIR}"; exit 1; }

script_list=$(find . -type f -name "*.sh")

echo "Do you want to remove instances of \"module load\" and \"module purge\"?"
echo "[Recommended] (y/n)"
read -r delete_module_lines

if [[ "${delete_module_lines}" == "y" ]]; then
    for file in $script_list; do
        sed -i "s/module load.*//g" "${file}"
        sed -i "s/module purge//g" "${file}"
    done
fi

echo "Do you want to remove SLURM directives associated with UoE's HPC?"
echo "[Recommended] (y/n)"
read -r delete_slurm_directives

if [[ "${delete_slurm_directives}" == "y" ]]; then
    for file in $script_list; do
        sed -i "s/#SBATCH -A Research_Project-MRC190311//g" "${file}"
        sed -i "s/#SBATCH -p mrcq//g" "${file}"
        sed -i "s/#SBATCH --mail-type=ED//g" "${file}"
    done
fi
