#!/bin/bash

## =================================================================================##
##                                                                                  ||
##                                     PREAMBLE                                     ||
##                                                                                  ||
## =================================================================================##
## PURPOSE:                                                                         ||
## Renames all source commands in scripts to the correct directory for local        ||
## machine (wherever the user clones it to).                                        ||
## Also gives the user the option to remove any lines beginning with "module",      ||
## these commands are unlikley to work on most systems. Ensure that the required    ||
## software is installed on your machine.                                           ||
## =================================================================================##
## AUTHOR: Sam Fletcher                                                             ||
## CONTACT: s.o.fletcher@exeter.ac.uk                                               ||
## CREATED: January 2024                                                            ||
## =================================================================================##

# Fail safe in case this file is not executed from the main directory of this
# repository.
script_path=$(dirname "$(readlink -f "$0")")

cd "$script_path" || exit 1

parent_directory=$(dirname "$(pwd)")

script_list=$(find . -type f -name "*.sh")
Rscript_list=$(find . -type f -name "*.R")

# Using @ delimiter to avoid excessive escaping of forward slashes in file paths
for file in $script_list; do
    sed -i "s@/lustre/projects[^\\]*@${parent_directory}@g" "${file}"
done
for file in $Rscript_list; do
    sed -i "s@/lustre/projects[^\\\"]*@${parent_directory}@g" "${file}"
done

echo "Do you want to remove instances of \"module load\" and \"module purge\"? (y/n)"
read -r delete_module_lines

if [[ "${delete_module_lines}" == "y" ]]; then
    for file in $script_list; do
        sed -i "s@module load.*@@g" "${file}"
        sed -i "s@module purge@@g" "${file}"
    done
fi
