#!/bin/bash
# File is not using .sh extension to avoid changing its own contents during
# sed lines.


configuration_directory=$1

source "${configuration_directory}/Config.txt" || \
{ echo "The configuration file does not exist in the specified location: \
${configuration_directory}"; exit 1; }

cd "${REPO_DIR}" || \
{ echo "The configuration file does not point to the correct script directory: \
${REPO_DIR}"; exit 1; }

## ============================== ##
##   CREATION OF FILE STRUCTURE   ##
## ============================== ##

mkdir -p  "${BINARY_DIR}" "${MODEL_DIR}" "${OPTIMUM_STATES_DIR}" \
    "${LD_ASSESSMENT_DIR}" "${BIG_MODELS_DIR}"

## ====================== ##
##   CONDA ENVIRONMENTS   ##
## ====================== ##

source "${CONDA_SHELL}" || { echo "Could not find conda shell at:
${CONDA_SHELL}"; exit 1; }
conda config --add channels bioconda
conda config --add channels conda-forge

conda create \
    --name ChromOptimise-R-java \
    --file "${REPO_DIR}/requirements-R-java.txt"

# Compatible version of bedtools with R (>2.27.1) fails to process bed files
# with genomic positions represented in scientific notation.
conda create \
    --name ChromOptimise-bedtools \
    --file "${REPO_DIR}/requirements-bedtools.txt"

conda create \
    --name ldsc \
    --file "${REPO_DIR}/requirements-ldsc.txt"

## ======== ##
##   RENV   ##
## ======== ##

conda activate ChromOptimise-R-java
Rscript -e "install.packages('renv', repo='https://cloud.r-project.org')"
Rscript -e "renv::restore(); library(data.table); print('success')"
conda deactivate

## ============================= ##
##   DELETE UOE SPECIFIC LINES   ##
## ============================= ##

script_list=$(find . -type f -name "*.sh")

echo "Do you want to remove SLURM directives associated with UoE's HPC?"
echo "[Recommended] (y/n)"
read -r delete_slurm_directives

if [[ "${delete_slurm_directives}" == "y" ]]; then
    for file in $script_list; do
        sed -i "s/#SBATCH -A Research_Project-MRC190311//g" "${file}"
        sed -i "s/#SBATCH -p mrcq//g" "${file}"
        sed -i "s/#SBATCH --mail-type=END//g" "${file}"
    done
fi
