#!/bin/bash
# File is not using .sh extension to avoid changing its own contents during
# sed lines.


configuration_directory=$1

source "${configuration_directory}/Config.txt" || \
{ echo "The configuration file does not exist in the specified location: \
${configuration_directory}"; exit 1; }

## ============================== ##
##   CREATION OF FILE STRUCTURE   ##
## ============================== ##

mkdir -p  "${BINARY_DIR}" "${MODEL_DIR}" "${OPTIMUM_STATES_DIR}" \
    "${LD_ASSESSMENT_DIR}" "${BIG_MODELS_DIR}"

## ============================= ##
##   DELETE UOE SPECIFIC LINES   ##
## ============================= ##

cd "${REPO_DIR}" || \
{ echo "The configuration file does not point to the correct script directory: \
${REPO_DIR}"; exit 1; }

script_list=$(find . -type f -name "*.sh")

echo "Do you want to remove SLURM directives associated with UoE's HPC?"
echo "[Recommended] (y/n)"
read -r delete_slurm_directives

if [[ "${delete_slurm_directives}" == "y" ]]; then
    for file in $script_list; do
        sed -i "s/#SBATCH -A Research_Project-MRC190311//g" "${file}"
        sed -i "s/#SBATCH -p mrcq//g" "${file}"
        sed -i "s/#SBATCH --mail-type=END//g" "${file}"
    done
fi
